Сorrected the regexp for the rightmost domain label
YADRO-KNS/obmc-yadro-netconfig pull request #17
Opened 2022-06-22 14:56 UTC by Smith-x86

The existing expression allows the user to specify a name
beginning with a digit, which contradicts RFC1738 (sec. 3.1):
"The rightmost domain label will never start with a digit".

This commit fixes that bug.

Signed-off-by: Vladimir Kuznetsov <v.kuznetsov@yadro.com>

2022-06-27 09:08 UTC, nest1ing requested changes
I see failed tests:
```
unknown file: Failure
C++ exception with description "Invalid argument: 123, expected IP address or FQDN" thrown in the test body.
[  FAILED  ] ArgumentsTest.IpOrFQDNPositive (37 ms)
```

2022-06-27 14:40 UTC, Smith-x86 commented
#

> I see failed tests:
> 
> ```
> unknown file: Failure
> C++ exception with description "Invalid argument: 123, expected IP address or FQDN" thrown in the test body.
> [  FAILED  ] ArgumentsTest.IpOrFQDNPositive (37 ms)
> ```

What tests? Where can I run them or see the results?
Regarding this error: the POSIX function inet_pton() checks IPv4 and IPv6 addresses. This function works only with ipv4 addresses in the classic dotted-decimal format "ddd.ddd.ddd.ddd". Thus it considers the argument "123" as incorrect. Also, "123" cannot be an FQDN.
As a result of the discussion it was decided not to introduce additional checks for IPv4 addresses in the form of a single number in binary, octal, decimal or hexadecimal notation.
I will add to the error message a request to enter the ipv4 address in dotted-decimal format.

2022-06-27 17:06 UTC, nest1ing commented
> What tests? Where can I run them or see the results?

See [README](https://github.com/YADRO-KNS/obmc-yadro-netconfig#testing)

Or you can install `sdbusplus` to your workstation, build this project and run tests.
I use the such way and just run:
```
meson build
ninja test -Cbuild
```

> Regarding this error: the POSIX function inet_pton() checks IPv4 and IPv6 addresses. This function works only with ipv4 addresses in the classic dotted-decimal format "ddd.ddd.ddd.ddd". Thus it considers the argument "123" as incorrect. Also, "123" cannot be an FQDN.
> As a result of the discussion it was decided not to introduce additional checks for IPv4 addresses in the form of a single number in binary, octal, decimal or hexadecimal notation.
> I will add to the error message a request to enter the ipv4 address in dotted-decimal format.

Yes, I believe You have to modify test sources to fix existing and probably enhance them to cover more variants.

2022-06-28 13:50 UTC, Smith-x86 commented
> Yes, I believe You have to modify test sources to fix existing and probably enhance them to cover more variants.

I changed/added some tests

2022-06-28 14:24 UTC, nest1ing approved these changes

2022-06-30 07:38 UTC, alatarum approved these changes

2022-08-28 18:01 UTC, AlexanderAmelkin approved these changes

2022-08-28 18:01 UTC, merged